import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(rootDir, relativePath), 'utf8'));
}

// Guards the single-source-of-truth invariant: every version surface must
// match package.json, otherwise web and desktop builds can diverge. @2026-07-09
test('version is aligned across package.json, neutralino.config.json and version.js', async () => {
  const pkgVersion = readJson('package.json').version;
  const configVersion = readJson('neutralino.config.json').version;
  const { APP_VERSION } = await import('../resources/js/version.js');

  assert.equal(configVersion, pkgVersion);
  assert.equal(APP_VERSION, pkgVersion);
});

test('version.js is regenerated by syncVersion', async () => {
  const { syncVersion } = await import('../scripts/sync-version.mjs');
  const versionModulePath = path.join(rootDir, 'resources', 'js', 'version.js');
  const before = fs.readFileSync(versionModulePath, 'utf8');

  const synced = syncVersion();

  const after = fs.readFileSync(versionModulePath, 'utf8');
  assert.equal(synced, readJson('package.json').version);
  assert.equal(after, before);
  assert.match(after, new RegExp(`APP_VERSION = '${synced.replace(/\./g, '\\.')}'`));
});
