import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

// Resolve from this file's location so importing scripts work from any cwd. @2026-07-09
const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packagePath = path.join(rootDir, 'package.json');
const neutralinoConfigPath = path.join(rootDir, 'neutralino.config.json');
const versionModulePath = path.join(rootDir, 'resources', 'js', 'version.js');

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function writeJson(filePath, obj) {
  fs.writeFileSync(filePath, `${JSON.stringify(obj, null, 2)}\n`, 'utf8');
}

function syncNeutralinoConfigVersion(version) {
  const config = readJson(neutralinoConfigPath);
  if (config.version !== version) {
    config.version = version;
    writeJson(neutralinoConfigPath, config);
    return true;
  }
  return false;
}

// The UI imports APP_VERSION instead of relying on a label patched into
// index.html, so desktop and web builds can never disagree. @2026-07-09
function syncVersionModule(version) {
  const content =
    `// Generated by scripts/sync-version.mjs — do not edit.\n` +
    `export const APP_VERSION = '${version}';\n`;
  const current = fs.existsSync(versionModulePath)
    ? fs.readFileSync(versionModulePath, 'utf8')
    : null;
  if (current === content) return false;
  fs.writeFileSync(versionModulePath, content, 'utf8');
  return true;
}

/**
 * Propagate the version from package.json to neutralino.config.json and
 * to the generated resources/js/version.js module.
 * @returns {string} the synced version
 */
export function syncVersion() {
  const pkg = readJson(packagePath);
  const version = String(pkg.version || '').trim();

  if (!version) {
    throw new Error('Versione mancante in package.json');
  }

  const changed = [];
  if (syncNeutralinoConfigVersion(version)) changed.push('neutralino.config.json');
  if (syncVersionModule(version)) changed.push('resources/js/version.js');

  if (changed.length === 0) {
    console.log(`[version-sync] Nessuna modifica (versione corrente: ${version})`);
  } else {
    console.log(`[version-sync] Versione ${version} sincronizzata su: ${changed.join(', ')}`);
  }

  return version;
}

const isDirectRun =
  process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;

if (isDirectRun) {
  try {
    syncVersion();
  } catch (error) {
    console.error('[version-sync] Errore:', error.message);
    process.exit(1);
  }
}
